version: "3.8"
services:
  playwright-chrome:
    image: ghcr.io/browserless/chrome:latest
    container_name: playwright-chrome
    restart: unless-stopped
    ports:
      - 20450:3000 # Expose l'API sur le port 20450
    environment:
      # Authentification par token
      - TOKEN=81d512d728f837dca958586a8e7387f5
      # Dimensions de l'écran (utile pour screenshots, PDF, etc.)
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=16
      # Paramètres de performance
      - TIMEOUT=60000 # Timeout des sessions (ms)
      - CONCURRENT=5 # Nombre max de sessions simultanées
      # Debug
      - ENABLE_DEBUGGER=false
      - EXIT_ON_HEALTH_FAILURE=true